//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ModelContainer1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ModelContainer1 object using the connection string found in the 'ModelContainer1' section of the application configuration file.
        /// </summary>
        public ModelContainer1() : base("name=ModelContainer1", "ModelContainer1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelContainer1 object.
        /// </summary>
        public ModelContainer1(string connectionString) : base(connectionString, "ModelContainer1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ModelContainer1 object.
        /// </summary>
        public ModelContainer1(EntityConnection connection) : base(connection, "ModelContainer1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Page> PageSet
        {
            get
            {
                if ((_PageSet == null))
                {
                    _PageSet = base.CreateObjectSet<Page>("PageSet");
                }
                return _PageSet;
            }
        }
        private ObjectSet<Page> _PageSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AllPages> AllPagesSet
        {
            get
            {
                if ((_AllPagesSet == null))
                {
                    _AllPagesSet = base.CreateObjectSet<AllPages>("AllPagesSet");
                }
                return _AllPagesSet;
            }
        }
        private ObjectSet<AllPages> _AllPagesSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PageSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPageSet(Page page)
        {
            base.AddObject("PageSet", page);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AllPagesSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAllPagesSet(AllPages allPages)
        {
            base.AddObject("AllPagesSet", allPages);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="AllPages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AllPages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AllPages object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="logo">Initial value of the Logo property.</param>
        /// <param name="colorR">Initial value of the ColorR property.</param>
        /// <param name="colorG">Initial value of the ColorG property.</param>
        /// <param name="colorB">Initial value of the ColorB property.</param>
        public static AllPages CreateAllPages(global::System.Int32 id, global::System.String logo, global::System.Int32 colorR, global::System.Int32 colorG, global::System.Int32 colorB)
        {
            AllPages allPages = new AllPages();
            allPages.Id = id;
            allPages.Logo = logo;
            allPages.ColorR = colorR;
            allPages.ColorG = colorG;
            allPages.ColorB = colorB;
            return allPages;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.String _Logo;
        partial void OnLogoChanging(global::System.String value);
        partial void OnLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorR
        {
            get
            {
                return _ColorR;
            }
            set
            {
                OnColorRChanging(value);
                ReportPropertyChanging("ColorR");
                _ColorR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColorR");
                OnColorRChanged();
            }
        }
        private global::System.Int32 _ColorR;
        partial void OnColorRChanging(global::System.Int32 value);
        partial void OnColorRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorG
        {
            get
            {
                return _ColorG;
            }
            set
            {
                OnColorGChanging(value);
                ReportPropertyChanging("ColorG");
                _ColorG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColorG");
                OnColorGChanged();
            }
        }
        private global::System.Int32 _ColorG;
        partial void OnColorGChanging(global::System.Int32 value);
        partial void OnColorGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColorB
        {
            get
            {
                return _ColorB;
            }
            set
            {
                OnColorBChanging(value);
                ReportPropertyChanging("ColorB");
                _ColorB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColorB");
                OnColorBChanged();
            }
        }
        private global::System.Int32 _ColorB;
        partial void OnColorBChanging(global::System.Int32 value);
        partial void OnColorBChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Page")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Page : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Page object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        public static Page CreatePage(global::System.Int32 id, global::System.String name, global::System.String content)
        {
            Page page = new Page();
            page.Id = id;
            page.Name = name;
            page.Content = content;
            return page;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marker_x
        {
            get
            {
                return _Marker_x;
            }
            set
            {
                OnMarker_xChanging(value);
                ReportPropertyChanging("Marker_x");
                _Marker_x = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Marker_x");
                OnMarker_xChanged();
            }
        }
        private global::System.String _Marker_x;
        partial void OnMarker_xChanging(global::System.String value);
        partial void OnMarker_xChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marker_y
        {
            get
            {
                return _Marker_y;
            }
            set
            {
                OnMarker_yChanging(value);
                ReportPropertyChanging("Marker_y");
                _Marker_y = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Marker_y");
                OnMarker_yChanged();
            }
        }
        private global::System.String _Marker_y;
        partial void OnMarker_yChanging(global::System.String value);
        partial void OnMarker_yChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marker_comment
        {
            get
            {
                return _Marker_comment;
            }
            set
            {
                OnMarker_commentChanging(value);
                ReportPropertyChanging("Marker_comment");
                _Marker_comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Marker_comment");
                OnMarker_commentChanged();
            }
        }
        private global::System.String _Marker_comment;
        partial void OnMarker_commentChanging(global::System.String value);
        partial void OnMarker_commentChanged();

        #endregion
    
    }

    #endregion
    
}
